# config/model/qwen25vl.yaml
defaults:
  - base
  - _self_

model_id: qwen-vl-max-latest  # 阿里云API中的模型名称  
api_key:  # 可以在这里设置API key，或通过环境变量DASHSCOPE_API_KEY设置
module_name: models.qwen
class_name: Qwen2_5VL